apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test3"
  description: "test3"
  tags:
    - sx
    - template
  links:
    - url: https://grafana.apps.cluster1.mcp.pitagora.at/d/KRlE7mE4z/4-golden-signals-sx-cnp?orgId=1&refresh=5s&var-namespace=suxess-it-dev&var-workload=test3&var-service=test3
      title: Grafana SRE Metrics
      icon: web
    - url: http://test3-suxess-it-dev.apps.cluster1.mcp.pitagora.at
      title: test3 Service Route
      icon: web
  annotations:
    github.com/project-slug: phac008/test3-gitops
    backstage.io/kubernetes-id: test3
    kubecost.com/deployment-name: test3
    argocd/app-name: test3-dev
    backstage.io/kubernetes-namespace: suxess-it-dev
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-selector: "(tags @> '4GoldenSignals')"
    grafana/overview-dashboard: "https://grafana.apps.cluster1.mcp.pitagora.at/d/KRlE7mE4z/4-golden-signals-sx-cnp?orgId=1&refresh=5s&var-namespace=suxess-it-dev&var-workload=test3&var-service=test3"
spec:
  type: service
  lifecycle: experimental
  owner: user:default/nikolaus.larcher
  system: system:test3
  dependsOn:
    - resource:argocd
