apiVersion: v1
kind: Service
metadata:
  name: test3
  namespace: suxess-it-dev
  labels:
    app: test3
    backstage.io/kubernetes-id: test3
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test3
  type: ClusterIP